# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_remove_userinfo_user_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
