# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_delete_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='ctime',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='uptime',
        ),
    ]
