# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20170715_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=32, verbose_name='用户名')),
                ('password', models.CharField(help_text='pwd', max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('test', models.EmailField(error_messages={'invalid': '请输入密码'}, max_length=19, null=True)),
                ('user_type_id', models.IntegerField(choices=[(1, '超级用户'), (2, '普通用户'), (3, '普普通用户')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='usergroup',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='uptime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
