# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scan_times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(db_index=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('ip', models.CharField(default='0.0.0.0', max_length=32)),
                ('port', models.IntegerField(default=80)),
                ('name', models.CharField(max_length=255)),
                ('verbose', models.CharField(max_length=1024)),
                ('types', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scan.type')),
            ],
        ),
        migrations.AddField(
            model_name='scan_times',
            name='websites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan.website'),
        ),
    ]
